package co.reservas.domain.shared;

/**
 * Códigos de error del contrato de la API (docs/modelo-datos-y-paquetes.md §3).
 */
public enum CodigoError {
    VALIDACION_FALLIDA,
    SOLICITUD_INVALIDA,
    SERVICIO_REQUERIDO,
    TOKEN_VERIFICACION_INVALIDO,
    NO_AUTENTICADO,
    CREDENCIALES_INVALIDAS,
    ACCESO_DENEGADO,
    CUENTA_NO_VERIFICADA,
    CUENTA_INACTIVA,
    SERVICIO_NO_ENCONTRADO,
    HORARIO_NO_ENCONTRADO,
    RECURSO_NO_ENCONTRADO,
    CATEGORIA_NO_ENCONTRADA,
    TIPO_RECURSO_NO_ENCONTRADO,
    RUTA_NO_ENCONTRADA,
    METODO_NO_PERMITIDO,
    EMAIL_YA_REGISTRADO,
    SERVICIO_YA_REGISTRADO,
    RECURSO_YA_REGISTRADO,
    HORARIO_SOLAPADO,
    HORARIO_CON_RESERVAS,
    TURNO_SIN_CUPO,
    RECURSO_NO_DISPONIBLE,
    RESERVA_SOLAPADA,
    RESERVA_EN_EL_PASADO,
    HORARIO_NO_DISPONIBLE,
    SERVICIO_NO_DISPONIBLE,
    BLOQUE_MENOR_A_DURACION,
    CUENTA_BLOQUEADA,
    ERROR_INTERNO
}
